# Generated by Django 4.1.4 on 2023-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=40)),
                ('stuemail', models.CharField(max_length=40)),
                ('stupass', models.CharField(max_length=40)),
            ],
        ),
    ]
